### PR TITLE
GT-1042 analytics updates

### PR DESCRIPTION
**Pull request by walsh9**
- Move the responsibility of handling audio events to the nypr-metrics service.
- Change a few click tracking events to the new GA formats
- Use nypr-metrics dataLayer service instead of directly manipulating the `dataLayer`.
- To track playlist position, we set the 'position' property on the audio object. This depends on updates in `nypr-metrics` (https://github.com/nypublicradio/nypr-metrics/pull/20) ~~and `nypr-audio-services` (https://github.com/nypublicradio/nypr-audio-services/pull/17)~~ to expose the audio position to the dataLayer.

The `position` property is currently only used for segmented playback, but I think it can also support the more general case of a representing an audio item's position within any kind of list. If using it in this way is a problem I can change the addons to use an new property for this. I like this way though, because it also opens up the ability to report audio positions within segmented audio if we ever want to do that.

(I also attempted to track playlist position from within `nypr-playlist` but ran into issues when the playlist passively switched over to a second audio item. There was no good place to update the position locally between the 'end' event and the automatic 'play' event if we wanted to handle this dataLayer value from the playlist itself.)

### CODE REVIEW

**Comment by walsh9** [comment]
@noslouch can you take a look at these changes when you get a chance? There are also two small related PRs linked in the description. Thanks.

**Review by noslouch — CHANGES_REQUESTED** [review]
I see what you're saying, but that `position` is actually the scrubber position, i.e. how many seconds into the track you want to start playback from, where `0` or `undefined` means start playback from the beginning, but `120` means start playback at 2 minutes in.

You can add whatever arbitrary values to the metadata key that you want, which means an update to `nypr-audio-services` isn't necessary. You can tweak the line where you create the `options` object like so and you'll be able to pull it out in the datalayer no problem.

```
let options = Object.assign({}, {metadata: {item, position}}, djOptions); // include `position` under the metadata key
```

**Comment by walsh9** [comment]
Ah I see now. Was trying to figure out what `position` was for and misread how `playSegmentedAudio()` worked. I'll add a new property into metadata.

**Review by noslouch — APPROVED** [review]
looks great! thanks for the changes. make sure to release a new metrics and update the package file accordingly.

**Pull request merged**
